server:
  port : 8180
logging:
  level:
    [no.sivertsensoftware]: DEBUG
    root: DEBUG
    web: DEBUG
    org:
      hibernate: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
  profiles:
        active: default
info:
  application:
    name: Contact Registration
    description: A Contact Registration application, ${app.name}
    author: Stig B. Sivertsen
    version: '@project.version@'
