server:
  port : 8082
  #contextPath: /api
  servlet:
    session:
      timeout: 20
logging:
  level:
    root: INFO
    web: INFO
    org:
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO
        data: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
spring:
  application:
    name: contact-registration
  datasource:
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: password
          name: contact
          url: jdbc:postgresql://db:5432/contact?createDatabaseIfNotExist=true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
info:
  application:
    name: Contact Registration
    description: A Contact Registration application, ${app.name}
    author: Stig B. Sivertsen
    version: '@project.version@'
